FILESEXTRAPATHS:prepend := "${THISDIR}/files:"
SRC_URI += "file://usb-gadget-adb.cfg"
SRC_URI += "file://overlayfs.cfg"
SRC_URI += "file://jffs2.cfg"
#SRC_URI += "file://display-drm.cfg"
SRC_URI += "file://console-debug.cfg"
SRC_URI += "file://virt-ext.cfg"
SRC_URI += "file://0001-arm-dts-alif-add-appkit-e7-board-support.patch"
